# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_association.ui'
#
# Created: Tue Jul 25 23:52:42 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1569, 1084)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_src_load_map = QtGui.QPushButton(self.centralwidget)
        self.pushButton_src_load_map.setGeometry(QtCore.QRect(10, 960, 151, 27))
        self.pushButton_src_load_map.setObjectName("pushButton_src_load_map")
        self.textEdit_src_path = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_src_path.setGeometry(QtCore.QRect(170, 960, 660, 30))
        self.textEdit_src_path.setReadOnly(False)
        self.textEdit_src_path.setObjectName("textEdit_src_path")
        self.pushButton_dst_load_map = QtGui.QPushButton(self.centralwidget)
        self.pushButton_dst_load_map.setGeometry(QtCore.QRect(10, 1000, 151, 27))
        self.pushButton_dst_load_map.setObjectName("pushButton_dst_load_map")
        self.textEdit_dst_path = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_dst_path.setGeometry(QtCore.QRect(170, 1000, 660, 30))
        self.textEdit_dst_path.setReadOnly(False)
        self.textEdit_dst_path.setObjectName("textEdit_dst_path")
        self.checkBox_show_association = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_show_association.setEnabled(False)
        self.checkBox_show_association.setGeometry(QtCore.QRect(1090, 970, 121, 21))
        self.checkBox_show_association.setChecked(False)
        self.checkBox_show_association.setObjectName("checkBox_show_association")
        self.pushButton_src_next = QtGui.QPushButton(self.centralwidget)
        self.pushButton_src_next.setGeometry(QtCore.QRect(910, 960, 70, 27))
        self.pushButton_src_next.setObjectName("pushButton_src_next")
        self.pushButton_src_previous = QtGui.QPushButton(self.centralwidget)
        self.pushButton_src_previous.setGeometry(QtCore.QRect(840, 960, 70, 27))
        self.pushButton_src_previous.setObjectName("pushButton_src_previous")
        self.pushButton_dst_next = QtGui.QPushButton(self.centralwidget)
        self.pushButton_dst_next.setGeometry(QtCore.QRect(910, 1000, 70, 27))
        self.pushButton_dst_next.setObjectName("pushButton_dst_next")
        self.pushButton_dst_previous = QtGui.QPushButton(self.centralwidget)
        self.pushButton_dst_previous.setGeometry(QtCore.QRect(840, 1000, 70, 27))
        self.pushButton_dst_previous.setObjectName("pushButton_dst_previous")
        self.graphicsView_src_map = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_src_map.setGeometry(QtCore.QRect(10, 10, 760, 910))
        self.graphicsView_src_map.setObjectName("graphicsView_src_map")
        self.graphicsView_dst_map = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_dst_map.setGeometry(QtCore.QRect(800, 10, 760, 910))
        self.graphicsView_dst_map.setObjectName("graphicsView_dst_map")
        self.checkBox_save_with_nxt_prv = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_save_with_nxt_prv.setGeometry(QtCore.QRect(1090, 990, 240, 21))
        self.checkBox_save_with_nxt_prv.setChecked(True)
        self.checkBox_save_with_nxt_prv.setObjectName("checkBox_save_with_nxt_prv")
        self.pushButton_reset = QtGui.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(1090, 1010, 111, 27))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 930, 1550, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(769, 10, 31, 911))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 920, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1140, 920, 91, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_save = QtGui.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(1210, 1010, 111, 27))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_instructions = QtGui.QPushButton(self.centralwidget)
        self.pushButton_instructions.setGeometry(QtCore.QRect(1440, 950, 111, 27))
        self.pushButton_instructions.setObjectName("pushButton_instructions")
        self.pushButton_about = QtGui.QPushButton(self.centralwidget)
        self.pushButton_about.setEnabled(False)
        self.pushButton_about.setGeometry(QtCore.QRect(1440, 980, 111, 27))
        self.pushButton_about.setObjectName("pushButton_about")
        self.checkBox_association_exists = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_association_exists.setEnabled(True)
        self.checkBox_association_exists.setGeometry(QtCore.QRect(1090, 950, 161, 21))
        self.checkBox_association_exists.setCheckable(True)
        self.checkBox_association_exists.setObjectName("checkBox_association_exists")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1569, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_src_load_map.setText(QtGui.QApplication.translate("MainWindow", "Load Source Map", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dst_load_map.setText(QtGui.QApplication.translate("MainWindow", "Load Destination Map", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_show_association.setText(QtGui.QApplication.translate("MainWindow", "show association", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_src_next.setText(QtGui.QApplication.translate("MainWindow", "Next>>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_src_previous.setText(QtGui.QApplication.translate("MainWindow", "<< Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dst_next.setText(QtGui.QApplication.translate("MainWindow", "Next>>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dst_previous.setText(QtGui.QApplication.translate("MainWindow", "<< Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_save_with_nxt_prv.setText(QtGui.QApplication.translate("MainWindow", "save with \"Previous\" and \"Next\" buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reset.setText(QtGui.QApplication.translate("MainWindow", "reset association", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Source Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Destination Map", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_instructions.setText(QtGui.QApplication.translate("MainWindow", "instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_about.setText(QtGui.QApplication.translate("MainWindow", "about", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_association_exists.setText(QtGui.QApplication.translate("MainWindow", "Association File Exist", None, QtGui.QApplication.UnicodeUTF8))

